### PR TITLE
Minor improvements + Make app translatable

### PR DESCRIPTION
**Pull request by NathanBnm**
Hello I made a few improvements to your project structure. 

I have standardized the file names by always using camel case and allowed your app to be translated.

Let me know if you have any questions :smile:

Once this PR merged, I'll be able to add French translation too!

### CODE REVIEW

**Comment by RajSolai** [comment]
Great, Thanks for your contribution @NathanBnm, All these days I don't know how to add translations, Thanks a lot.

**Comment by NathanBnm** [comment]
In order to make some strings translatable you just have to surround them like this: `_("Translate me")`

If you want to put some variables too you can use it in combination with the `printf` method as the following: `_("%d minutes").printf(minutes_variable)`

Then in order to update translation files you just have to run the following commands inside the meson build folder:

```
# For main translations
ninja your-app-id-update-po
# For metadata translations
ninja extra-update-po
```

**Comment by NathanBnm** [comment]
For more details you can see https://docs.elementary.io/develop/writing-apps/our-first-app/translations

**Comment by RajSolai** [comment]
_Thanks a Lot Pal :)_

**Pull request merged**
